[package]
name = "framework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.7"
anyhow = "1.0"
bitvec = "0.22"
colored = "2.0"
thiserror = "1.0"
tinyvec = "1.5"
ureq = "2.3"
